overrides:
  '@ethersphere/bee-js': 'github:Apiary-Suite/bee-js'

allowBuilds:
  '@ethersphere/bee-js': true
  '@parcel/watcher': true
  unrs-resolver: true

blockExoticSubdeps: false

minimumReleaseAgeExclude:
  - '@solarpunkltd/comment-system@1.9.5'
